### ISSUE TITLE
build errors when compiling bump examples in Xcode

### ISSUE THREAD

**Issue by jholub15** [BodyViz/bump#3]
After following all the instructions for building on the Wiki, there is one error that I am finding in the build process when the Xcode project tries to build the examples. The issue seems to be that the bump exe is never actually built before the examples try to link to it. If I removed examples from the build using the CMake GUI, everything builds just fine and the bump exe is created and installed. If I select to build examples as well as the frameworks, the exe is never created and Xcode throws an error trying to link to it.

I've started looking in the CMake files and haven't seen anything yet, but I will keep looking.

**Comment by cnoon** [comment]
I was able to reproduce this behavior on my machine. I'll take it from here and see if I can't figure out why the binary seems to be getting linked properly but not installed into the framework.

**Comment by cnoon** [comment]
Got it all figured out. The issue was that you cannot have the CMake_CONFIGURATION_TYPE set to both Debug;Release when building frameworks. It needs to be one or the other. Everything is now working properly and Joe is going to update the wiki so no one else has this issue.

**Comment by jholub15** [comment]
Wiki updated to say if building a .framework, you can only build one at a time.
