### ISSUE TITLE
String::toFloat and hidden characters

### ISSUE THREAD

**Issue by jholub15** [BodyViz/bump#8]
The String::toFloat function is bombing out on me when I am trying to convert a string "0.90565435\r" to a float. The exception is being thrown by libc++abi.dylib and not bump or boost. I arrived here by parsing data from a text file with the "\r" hidden character at the end.

I'm throwing this in the question section just as a reference that this happens. I don't think this class should try and interpret what the user wants to do with hidden characters, but it might be worth looking into why bump isn't throwing "TypeCastError("Cannot convert string to float", BUMP_LOCATION);" and see if this can be changed so users know what's happening.

**Comment by cnoon** [comment]
This is a great thing to add to the bump::StringTest::testToFloat() unit test. I'm pretty sure that all that will need to happen is we catch the exception being thrown by boost or the C++ runtime. I can't remember exactly how this works, but I think it uses boost lexical casts to handle it.

**Comment by jholub15** [comment]
I can add to this a little and say that this same this occurs when it's an empty string. So it's not just hidden characters. And yes it's boost::lexical_cast that is being used. Doesn't look like boost::bad_lexical_cast is being called.

**Comment by cnoon** [comment]
This is probably an issue with all the bump::String::toSomething() methods. Just an edge case that I didn't consider or test properly in the first round. It would be great if you could dig into this and fix it Joe. Just let me know if you need any help figuring out the patches. My guess is that a bad_lexical_cast is being thrown and we need to catch it, then throw a bump::TypeCastError instead. I'm going to assign this ticket to you for now. If you need anything just give me a call.

**Comment by jholub15** [comment]
Righty-o :)

**Comment by jholub15** [comment]
Ok, so as I'm looking at this. The unit test for toFloat uses a empty string as one of the test cases where it is looking for a bump::TypeCastError like it is suppose to and it works just fine and passes. So I created another sample app that just tries to convert an empty string to a float and it throws the same error.

The error thrown is C++ "libc++abi.dylib: terminate called throwing an exception" and it is the actual throwing of the bump::TypeCastError. It's catching the boost::bad_lexical_cast and trying to throw the TypeCastError. There is no problem in creating the bump::TypeCastError itself, just on the line throwing the TypeCastError object.

That is what I have so far, I will keep looking. Comments are welcome.

**Comment by cnoon** [comment]
Talked to Joe about this particular issue. The problem was that in his app, he was not properly try/catching the exception being thrown. Here's an example of how to make sure you catch and handle the error in your application appropriately.

``` cpp

try
{
    bump::String float_str("0.578\r");
    float float_value = float_str.toFloat();
}
catch (const bump::TypeCastError& error)
{
    std::cout << error.description() << std::endl;
    // Scratch your head and figure out what to do now...
}
```

I'm going to close this ticket out since it doesn't appear there is actually a bug in the Bump logic. We'll re-open it if there is.
