### ISSUE TITLE
Generating static libs on Mac

### ISSUE THREAD

**Issue by jholub15** [BodyViz/bump#9]
Trying to build static libraries on Mac to use with a new project, I'm getting an error when building the Test-bumpCryptographicHash because it can't link to the SHA-1 library. When going into the Xcode project and adding the sha-1 library (which builds) the test project will build and run.

The .a files all build and do not throw any errors until trying to build the tests or use the libbump.a file in a project. I tried this with another project and got the same link error because it can't find the aha-1 library.

I am by no means intelligent when it comes to building libraries, but my understanding of how this static library was meant to be built was to build all the aha-1 library functionality into it and only require the libbump.a file.

This occurs when building both the debug and release versions. Building the frameworks seems to work just fine, although I have not tried implementing any crypto functionality with them.

Attached is my bump settings in cmake:
![Screen Shot 2013-02-04 at 5 46 59 PM](https://f.cloud.github.com/assets/718650/125818/40446ba6-6f25-11e2-83db-6ffd2fb0841e.png)

**Comment by cnoon** [comment]
This is probably a bug in the CMake configuration. It works properly when using frameworks and dylibs. For now, I'd suggest using either of those until this can get resolved.

**Comment by jholub15** [comment]
I think I figured out what needs to be done in Xcode at least. In the static lib Build Settings, under Linking, there is an option for "Perform Single-Object Prelink" that should be set to yes. Then directly underneath that, the "Prelink libraries" path should be set to the libsmallsha1.a file that was just compiled.

This lets the entire "install" build process work including the Cryptographic test and example. I also tested this library with our SOMViz code that I can working on and it now builds just fine and seems to run.

I will look into what needs to be done in cmake.

**Comment by cnoon** [comment]
You're going to want to figure out what needs to be changed in the LINK_3RD_PARTY and SETUP_3RD_PARTY_LIBRARY macros in the BumpMacroUtils.cmake file. There probably just needs to be a check to do something slightly different there is Bump is being compiled as static libs.

**Comment by jholub15** [comment]
So doing some research on this, everything seems to say there is one way to do this. When adding the source files for the library there needs to be a "OBJECT" flag thrown in so that cmake compiles a .o file and not the full .a (e.g. ADD_LIBRARY(<name> OBJECT <source_files>)). Then when adding it to the parent library you use ADD_LIBRARY( <lib_name> <lib_source files> $<TARGET_OBJECTS:<name>>

This should build everything into a single .a file.

I'm trying this but so far everything I try with this results in the same cmake error:

CMake Error: Target smallsha1 has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
  smallsha1_LIB_DEPENDS
from the cache.

I've tried building a very simple standalone app using this procedure and it works. I'm still digging but I'm running out of ideas to try right now. The error always shows up when the "OBJECT" flag is include. The comment about removing the smallsha1_LIB_DEPENDS variable is not a lot of help as far as I can see. The variable is set exactly the same whether the "OBJECT" flag is included or not.

Thoughts from anyone?

**Comment by cnoon** [comment]
Here are some threads I've found, maybe they'll shed some light (maybe you've already read these):
- http://www.cmake.org/pipermail/cmake/2011-February/042893.html
- http://mail.kde.org/pipermail/kde-buildsystem/2006-October/003419.html
- http://stackoverflow.com/questions/4786861/cmake-link-external-c-library

I also have no problem with simply moving the smallsha1 header and source files into the CMake file for building the Bump library. They can just be listed as source and header files for the library (which they technically are). This will for sure solve the problem and doesn't bother me one bit. This is how that last link suggests to do it and was one of the ways I originally considered. I just looked at the repository and here's what I would try out:
- Get rid of the 3rdParty directory structure altogether
- Create new include/smallsha1 and src/smallsha1 directories
- Move the sha1.cpp and sha1.h files into their appropriate locations
- Add these header and source files into the src/bump/CMakeLists.txt file and put them at the beginning of both lists
- Remove the TARGET_3RD_PARTY_LIBRARIES call and the macro from the BumpMacroUtils.cmake file

Give it a go...I'm guessing this should fix the problem completely and it definitely the way I should have done it in the first place. I would not have committed the whole smallsha1.a to bump.framework CMake solution if I would have realized that approach doesn't work for generating a static bump.a library. Let me know if that's enough info to get going. If not just give me a call.

**Comment by jholub15** [comment]
That will definitely solve the issue. I've made the modifications and it builds and installs everything (libs, tests, examples). I will test it out the other builds (dylibs, frameworks) and test it in an app to make sure everything is working before I push it up.

**Comment by cnoon** [comment]
Rock on brotha...let me know when you've got it pushed up!

**Comment by jholub15** [comment]
Just made a pull request.

I tested and built all versions of dylibs, frameworks, and static libs with this. I then tested the CryptographicHash class in a test app and it worked just fine with adding boost and bump to the project.
